# global parameters
# all pins use wiringPi numbering scheme

# arduino parameters
arduino:
  i2c_address: 0x04 # i2c protocol address

# driving control parameters
driving:
  k_collision_brake: 0.5 # collision avoidance braking constant (larger values = harsher braking  w.r.t. distance to object (linear)) [0 to 1]
  k_collision_steer: 70.0 # collision avoidance steering constant (larger values = harsher steering w.r.t. distance to object (linear)) [0 to infinity]
  k_throttle_decay: -1.6 # throttle decay constant (smaller values = harsher throttle cut w.r.t. steering angle (exponential)) [0 to -infinity]
  maximum_throttle: 25.0
  minimum_throttle: 18.0

# driving aid control parameters
driving_aids:
  collision_avoidance_autonomous: true
  collision_avoidance_manual: true

# controller parameters
joy_node:
  dev: "/dev/input/js0"

# indicator LED parameters
led:
  indicator_pin: 23
  mode_blue_pin: 25
  mode_green_pin: 27
  mode_red_pin: 24

mapping:
  output_file_path: "/home/corey/avc_ws/gpsWaypoints.csv"

proximity_sensor:
  front:
    echo_pin: 4
    trigger_pin: 5
  left:
    echo_pin: 21
    trigger_pin: 22
  right:
    echo_pin: 31
    trigger_pin: 26

# steering servo parameters
steering_servo:
  max_rotation_angle: 30.0 # max rotation from neutral position in either direction [deg]
