# global parameters

# button parameters
button:
  emergency_stop:
    input_pin: 255

joy_node:
  dev: "/dev/input/js0"

led:
  indicator_pin: 254
  mode_blue_pin: 249
  mode_green_pin: 250
  mode_red_pin: 251
  power_pin: 248

switch:
  mode:
    mapping_pin: 252
    running_pin: 253
