# global parameters
# all pins use wiringPi numbering scheme

# arduino parameters
arduino:
  i2c_address: 0x04 # i2c protocol address

driving:
  k_throttle_decay: -1.6 # throttle decay constant (throttle % = e^(steering_angle / max_rotation_angle * k_throttle_decay))
  maximum_throttle: 25
  minimum_throttle: 12

# controller parameters
joy_node:
  dev: "/dev/input/js0"

# indicator LED parameters
led:
  indicator_pin: 23
  mode_blue_pin: 25
  mode_green_pin: 27
  mode_red_pin: 24

mapping:
  output_file_path: "/home/corey/avc_ws/gpsWaypoints.csv"

proximity_sensor:
  front:
    echo_pin: 4
    trigger_pin: 5
  left:
    echo_pin: 21
    trigger_pin: 22
  right:
    echo_pin: 31
    trigger_pin: 26

# steering servo parameters
steering_servo:
  max_rotation_angle: 30.0 # max rotation from neutral position in either direction [deg]
