# global parameters

# arduino parameters
arduino:
  i2c_address: 0x04 # i2c protocol address

# controller parameters
joy_node:
  dev: "/dev/input/js0"

# indicator LED parameters
led:
  indicator_pin: 1
  mode_blue_pin: 28 # pin may not work on Pi 3 B
  mode_green_pin: 27
  mode_red_pin: 29 # pin may not work on Pi 3 B

mapping:
  output_file_path: "/home/corey/avc_ws/gpsWaypoints.csv"

proximity_sensor:
  front:
    echo_pin: 4 # (using wiringPi numbering scheme)
    trigger_pin: 5 # (using wiringPi numbering scheme)
  left:
    echo_pin: 255 # (using wiringPi numbering scheme)
    trigger_pin: 255 # (using wiringPi numbering scheme)
  right:
    echo_pin: 255 # (using wiringPi numbering scheme)
    trigger_pin: 255 # (using wiringPi numbering scheme)

# steering servo parameters
steering_servo:
  max_rotation_angle: 30.0 # max rotation from neutral position in either direction [deg]
