arduino_output_node:
  refresh_rate: 50

esc_node:
  esc_max_value: 2000
  esc_min_value: 1000
  esc_neutral_value: 1350
  refresh_rate: 50

servoblaster:
  esc_servo_number: 0 # GPIO pin #4 (BCM)
  force_output_time: 0.5 # time allowed before a servo output is forced [s]
  sb_driver_path: "/dev/servoblaster"
  ss_servo_number: 1 # GPIO pin #17 (BCM)

steering_servo_node:
  ss_max_right: 1700
  ss_max_left: 950
  ss_neutral_value: 1350
  refresh_rate: 50
