# sensor parameters
# all refresh rates are given in hertz

# NOT YET IMPLEMENTED
# GPS parameters
# gps:
#   refresh_rate: 10.0

# IMU parameters
imu:
  refresh_rate: 10.0
  slerp_power: 0.02

# NOT YET IMPLEMENTED
# laser parameters
# laser:

# proximity sensor parameters
proximity_sensor:
  echo_pin: 4 # (using wiringPi numbering scheme)
  field_of_view: 0.3665 # (in radians)
  min_range: 0.5 # (in meters)
  max_range: 2.0 # (in meters)
  name: hc-sr04
  radiation_type: 0 # (0 = ultrasonic, 1 = infrared)
  refresh_rate: 10.0
  timeout: 25.0 # (in milliseconds)
  trigger_pin: 5 # (using wiringPi numbering scheme)
